//AddAbility(class_name, type, json_id)

DoAbility(SingleShotAbility, HELLS_BUBBLE, "hells_bubble_ability")
DoAbility(SingleShotAbility, HELLS_DART, "hells_dart_ability")
DoAbility(HellsDashAbility, HELLS_DASH, "hells_dash")
DoAbility(HellsRainAbility, HELLS_RAIN, "hells_rain")

DoAbility(NaturesRageAbility, NATURES_RAGE, "natures_rage")
DoAbility(SingleShotAbility, FOREST_LEAF, "forest_leaf_ability")
DoAbility(SelfBuffAbility, FOREST_NIGHT, "forest_night_ability")
DoAbility(GoldenLeafAbility, GOLDEN_LEAF, "golden_leaf_ability")