//AddAbility(class_name, type, json_id)

DoAbility(SingleShotAbility, HELLS_BUBBLE, "hells_bubble_ability")
DoAbility(SingleShotAbility, HELLS_DART, "hells_dart_ability")
DoAbility(HellsDashAbility, HELLS_DASH, "hells_dash")
DoAbility(HellsRainAbility, HELLS_RAIN, "hells_rain")

DoAbility(NaturesRageAbility, NATURES_RAGE, "natures_rage")
DoAbility(ForestLeafAbility, FOREST_LEAF, "forest_leaf_ability")
DoAbility(SelfBuffAbility, FOREST_NIGHT, "forest_night_ability")
DoAbility(GoldenLeafAbility, GOLDEN_LEAF, "golden_leaf_ability")

DoAbility(ShotgunShotAbility, FISH_SHOTGUN, "fish_shotgun")
DoAbility(FishingGaunletAbility, FISHING_GAUNLET, "fishing_gaunlet_ability")
DoAbility(PassiveAbility, FISH_LIFESTEAL, "fish_lifesteal_ability")
DoAbility(MeatShieldAbility, MEAT_SHIELD, "meat_shield_ability")
