//DoBuff(class_name, type, json_id)

DoBuff(RechargeAbilityBuff, RECHARGE_ABILITY, "recharge_ability")
DoBuff(StormBuff, STORM, "storm")
DoBuff(PhasedBuff, LOBBY_PHASED, "lobby_phased")
DoBuff(RevealBuff, STANDARD_REVEAL, "standard_reveal")

DoBuff(RootBuff, HELLS_DART_ROOT, "hells_dart_root")

DoBuff(SlowBuff, FOREST_SLOW, "forest_slow")
DoBuff(SilenceBuff, FOREST_SILENCE, "forest_silence")
DoBuff(StunBuff, NATURES_ROCK_STUN, "natures_rock_stun")
DoBuff(InvisBuff, FOREST_NIGHT, "forest_night")

DoBuff(LifestealBuff, FISH_LIFESTEAL, "fish_lifesteal")
DoBuff(RootBuff, GAUNLET_ROOT, "gaunlet_root")
DoBuff(FishingGaunletBuff, FISHING_GAUNLET, "fishing_gaunlet_buff")
DoBuff(MeatShieldBuff, MEAT_SHIELD, "meat_shield")
